# **Chronic Health Prediction**

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
encoding = 'latin1'

data = pd.read_csv('/content/drive/MyDrive/BRFSS Project/Reduced_Dataset.csv', encoding=encoding, error_bad_lines=False)

<ipython-input-5-7a93a06c1586>:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv('/content/drive/MyDrive/BRFSS Project/Reduced_Dataset.csv', encoding=encoding, error_bad_lines=False)
<ipython-input-5-7a93a06c1586>:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/content/drive/MyDrive/BRFSS Project/Reduced_Dataset.csv', encoding=encoding, error_bad_lines=False)

In [62]:
df = data.copy()

In [63]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489346,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
489347,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
489348,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
489349,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
489350,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

**Dropping rows with less common responses**

In [64]:
# Iterate through columns with datatype 'object'
for column in df.select_dtypes(include='object').columns:
    # Count the occurrences of each unique value in the column
    value_counts = df[column].value_counts()

    # Get the unique values that occur less than 20 times
    values_to_drop = value_counts[value_counts < 50].index

    # Drop the rows where the column value is in values_to_drop
    df = df[~df[column].isin(values_to_drop)]

# Reset the index after dropping rows
df = df.reset_index(drop=True)

In [65]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
481964,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
481965,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
481966,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
481967,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

**Converting columns containing numeric values to int/float**

In [66]:
# Function to check if a value is numeric
def is_numeric(value):
    try:
        float(value)
        return True
    except ValueError:
        return False

# Convert object-type columns to int or float based on numeric content in at least one row
for column in df.select_dtypes(include='object').columns:
    # Check if any row in the column has purely numeric values
    if any(df[column].apply(is_numeric)):
        # Convert to float
        df[column] = pd.to_numeric(df[column], errors='coerce')

        # Convert to int if there are no decimal values, otherwise to float
        df[column] = df[column].astype(int) if all(pd.notna(value) and value.is_integer() for value in df[column]) else df[column].astype(float)

In [67]:
# datatype of all the columns
for column in df.columns:
    print(f"{column}: {df[column].dtypes}")

X_state: object
stateres: object
genhlth: object
poorhlth: float64
physhlth: float64
menthlth: float64
hlthpln1: object
persdoc2: object
medcost: object
sleptim1: float64
bphigh4: object
bpmeds: object
toldhi2: object
cvdinfr4: object
cvdcrhd4: object
cvdstrk3: object
asthma3: object
chcocncr: object
havarth3: object
addepev2: object
chckidny: object
diabete3: object
educa: object
marital: object
employ1: object
income2: object
weight2: int64
height3: float64
renthom1: object
qlactlm2: object
useequip: object
blind: object
smoke100: object
smokday2: object
usenow3: object
alcday5: float64
avedrnk2: float64
fruitju1: float64
fruit1: float64
fvbeans: float64
fvgreen: float64
fvorang: float64
vegetab1: float64
exeroft1: float64
seatbelt: object
sex: object

In [68]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
481964,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
481965,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
481966,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
481967,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

In [69]:

df.rename(columns={
    'cvdinfr4': 'Heart Attack',
    'cvdcrhd4': 'Angina Or Coronary Heart Disease',
    'cvdstrk3': 'Stroke',
}, inplace=True)

In [70]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
481964,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
481965,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
481966,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
481967,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

# **Model 1 with all input variables:**

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler
import pandas as pd
import warnings

# Ignore convergence warnings
warnings.filterwarnings("ignore", category=UserWarning)

# Assume df is your dataframe with relevant columns

# List of chronic conditions
chronic_conditions = ['Heart Attack', 'Angina Or Coronary Heart Disease', 'Stroke']

for condition in chronic_conditions:
    # Encode target variable
    label_encoder = LabelEncoder()
    df[condition] = label_encoder.fit_transform(df[condition])

    # Encode categorical columns
    categorical_columns = df.select_dtypes(include=['object']).columns
    for col in categorical_columns:
        df[col] = label_encoder.fit_transform(df[col])

    # Split the data
    X = df.drop([condition], axis=1)  # Features
    y = df[condition]  # Target variable

    # Feature scaling
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

    # Train Logistic Regression model
    model = LogisticRegression(max_iter=1000, solver='liblinear')
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    confusion_mat = confusion_matrix(y_test, y_pred)

    print(f"Results for {condition}:")
    print(f"Accuracy: {accuracy}")
    print("Confusion Matrix:")
    print(confusion_mat)
    print("Classification Report:")
    print(classification_rep)
    print("\n")

Results for Heart Attack:
Accuracy: 0.9448617133846505
Confusion Matrix:
[[89568  1115]
 [ 4200  1511]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97     90683
           1       0.58      0.26      0.36      5711

    accuracy                           0.94     96394
   macro avg       0.77      0.63      0.67     96394
weighted avg       0.93      0.94      0.94     96394



Results for Angina Or Coronary Heart Disease:
Accuracy: 0.9446646056808515
Confusion Matrix:
[[89487  1146]
 [ 4188  1573]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97     90633
           1       0.58      0.27      0.37      5761

    accuracy                           0.94     96394
   macro avg       0.77      0.63      0.67     96394
weighted avg       0.93      0.94      0.94     96394



Results for Stroke:
Accuracy: 0.9585970081125381
Confusion Matrix:
[[92299   140]
 [ 3851   104]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98     92439
           1       0.43      0.03      0.05      3955

    accuracy                           0.96     96394
   macro avg       0.69      0.51      0.51     96394
weighted avg       0.94      0.96      0.94     96394

In [61]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,0,0,1,30.00000,30.0,29.000000,1,2,0,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,0,0
1,0,0,2,5.30023,0.0,0.000000,1,2,0,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,0,0
2,0,0,2,0.00000,3.0,2.000000,1,2,0,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,0,0
3,0,0,4,0.00000,2.0,0.000000,1,2,0,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,0,0
4,0,0,2,0.00000,10.0,2.000000,1,2,0,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,40,0,1,0.00000,14.0,15.000000,1,0,0,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,0,0
481964,40,0,2,5.30023,0.0,0.000000,1,2,0,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,0,1
481965,40,0,1,0.00000,15.0,20.000000,1,0,1,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,0,0
481966,40,0,4,5.30023,0.0,0.000000,1,2,0,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,0,0
481967,40,0,2,30.00000,30.0,3.380493,1,0,0,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,0,1

# **Model 2 with 15 input features:**

In [71]:
import pickle
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split



# Define the features for chronic conditions
selected_features_chronic_conditions = ['bphigh4', 'toldhi2', 'chcocncr', 'havarth3', 'addepev2', 'employ1', 'weight2', 'height3', 'renthom1', 'qlactlm2', 'diabete3', 'smoke100', 'asthma3', 'alcday5', 'sex']

# Define the target variables for each chronic condition
chronic_conditions = ['Heart Attack', 'Angina Or Coronary Heart Disease', 'Stroke']

for condition in chronic_conditions:
    print(f"\nResults for {condition}:")

    # Encode the target variable
    label_encoder = LabelEncoder()
    df[condition] = label_encoder.fit_transform(df[condition])

    # Encode categorical columns
    categorical_columns = df.select_dtypes(include=['object']).columns
    for col in categorical_columns:
        df[col] = label_encoder.fit_transform(df[col])

    # Separate features and target variable
    X = df[selected_features_chronic_conditions]
    y = df[condition]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Perform oversampling using SMOTE
    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

    # Train Logistic Regression model
    model = LogisticRegression()
    model.fit(X_resampled, y_resampled)

    # Make predictions
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    confusion_mat = confusion_matrix(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)

    print(f"Accuracy: {accuracy}")
    print(f"Confusion Matrix:\n{confusion_mat}")
    print(f"Classification Report:\n{classification_rep}")

    # Save the model using pickle
with open('chronic_condition_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

Results for Heart Attack:
Accuracy: 0.6888188061497603
Confusion Matrix:
[[62719 27964]
 [ 2032  3679]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.69      0.81     90683
           1       0.12      0.64      0.20      5711

    accuracy                           0.69     96394
   macro avg       0.54      0.67      0.50     96394
weighted avg       0.92      0.69      0.77     96394


Results for Angina Or Coronary Heart Disease:
Accuracy: 0.7074714193829491
Confusion Matrix:
[[64344 26289]
 [ 1909  3852]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.71      0.82     90633
           1       0.13      0.67      0.21      5761

    accuracy                           0.71     96394
   macro avg       0.55      0.69      0.52     96394
weighted avg       0.92      0.71      0.78     96394


Results for Stroke:
Accuracy: 0.6953648567338216
Confusion Matrix:
[[64647 27792]
 [ 1573  2382]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.70      0.81     92439
           1       0.08      0.60      0.14      3955

    accuracy                           0.70     96394
   macro avg       0.53      0.65      0.48     96394
weighted avg       0.94      0.70      0.79     96394