In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
import pandas as pd

# Make sure to mount Google Drive if you are using Colab
# from google.colab import drive
# drive.mount('/content/drive')

# Specify the correct file path
file_path = '/content/gdrive/My Drive/Colab Notebooks/brfss2013.csv'

# Read the CSV file
df = pd.read_csv(file_path, encoding='latin1')

<ipython-input-33-d0386a0753ab>:11: DtypeWarning: Columns (12,15,51,54,103,104,105,106,109,112,113,114,119,120,121,122,123,124,126,127,128,131,133,135,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,178,179,180,181,182,183,184,185,186,187,188,189,191,192,193,194,195,196,198,200,201,202,203,204,205,206,207,208,209,210,211,212,213,217,227,228,229,230,231,313) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')

In [ ]:
print(df.head())

   Unnamed: 0  X_state    fmonth      idate    imonth  iday   iyear  \
0           1  Alabama   January  1092013.0   January   9.0  2013.0
1           2  Alabama   January  1192013.0   January  19.0  2013.0
2           3  Alabama   January  1192013.0   January  19.0  2013.0
3           4  Alabama   January  1112013.0   January  11.0  2013.0
4           5  Alabama  February  2062013.0  February   6.0  2013.0

              dispcode         seqno         X_psu  ...  \
0  Completed interview  2.013001e+09  2.013001e+09  ...
1  Completed interview  2.013001e+09  2.013001e+09  ...
2  Completed interview  2.013001e+09  2.013001e+09  ...
3  Completed interview  2.013001e+09  2.013001e+09  ...
4  Completed interview  2.013001e+09  2.013001e+09  ...

                      X_pastae1  \
0  Did not meet both guidelines
1  Did not meet both guidelines
2  Did not meet both guidelines
3  Did not meet both guidelines
4  Did not meet both guidelines

                                           X_lmtact1  \
0  Told have arthritis and have limited usual act...
1                       Not told they have arthritis
2  Told have arthritis and have limited usual act...
3                       Not told they have arthritis
4                       Not told they have arthritis

                                   X_lmtwrk1  \
0  Told have arthritis and have limited work
1               Not told they have arthritis
2  Told have arthritis and have limited work
3               Not told they have arthritis
4               Not told they have arthritis

                                           X_lmtscl1  \
0  Told have arthritis and social activities limi...
1                       Not told they have arthritis
2  Told have arthritis and social activities limi...
3                       Not told they have arthritis
4                       Not told they have arthritis

                                X_rfseat2              X_rfseat3  X_flshot6  \
0  Always or almost always wear seat belt  Always wear seat belt        NaN
1  Always or almost always wear seat belt  Always wear seat belt        NaN
2  Always or almost always wear seat belt  Always wear seat belt        NaN
3  Always or almost always wear seat belt  Always wear seat belt        NaN
4  Always or almost always wear seat belt  Always wear seat belt         No

   X_pneumo2  X_aidtst3 X_age80
0        NaN         No    60.0
1        NaN        Yes    50.0
2        NaN        Yes    55.0
3        NaN         No    64.0
4         No         No    66.0

[5 rows x 331 columns]

In [ ]:
df.shape

(491775, 331)

In [ ]:
# Check and display columns with missing values
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]
print("Missing Values Count for Columns with Missing Values:")
print(missing_values)

Missing Values Count for Columns with Missing Values:
fmonth            3
idate             2
imonth            3
iday              3
iyear             5
              ...
X_rfseat3     38941
X_flshot6    343079
X_pneumo2    349054
X_aidtst3     54595
X_age80          11
Length: 329, dtype: int64

In [ ]:
missing_values = df.isnull().sum()
print("Missing Values Count for Each Column:")
pd.set_option('display.max_rows', None)  # Display all rows
print(missing_values)
pd.reset_option('display.max_rows')  # Reset row display options

Missing Values Count for Each Column:
Unnamed: 0         0
X_state            0
fmonth             3
idate              2
imonth             3
iday               3
iyear              5
dispcode           5
seqno              3
X_psu              2
ctelenum          41
pvtresd1      131636
colghous      491730
stateres      131642
cellfon3      135151
ladult        491737
numadult      131651
nummen        131650
numwomen      131650
genhlth         1985
physhlth       10957
menthlth        8627
poorhlth      243153
hlthpln1        1904
persdoc2        1801
medcost         1221
checkup1        6305
sleptim1        7387
bphigh4         1420
bpmeds        293201
bloodcho        9010
cholchk        73178
toldhi2        71662
cvdinfr4        2587
cvdcrhd4        4423
cvdstrk3        1467
asthma3         1559
asthnow       426435
chcscncr        1309
chcocncr        1148
chccopd1        2724
havarth3        2970
addepev2        2289
chckidny        1721
diabete3         832
veteran3         746
marital         3420
children        2274
educa           2274
employ1         3386
income2        71426
weight2        20675
height3         7623
numhhol2      134365
numphon2      475603
cpdemo1       135081
cpdemo4       227079
internet        4926
renthom1        8448
sex                7
pregnant      414790
qlactlm2       11329
useequip       10317
blind          11079
decide         12990
diffwalk       12764
diffdres       12122
diffalon       13350
smoke100       14920
smokday2      276983
stopsmk2      415421
lastsmk2      354497
usenow3        14018
alcday5        19644
avedrnk2      260590
drnk3ge5      260444
maxdrnks      264958
fruitju1       36208
fruit1         33798
fvbeans        37492
fvgreen        35157
fvorang        36563
vegetab1       38947
exerany2       34029
exract11      160948
exeroft1      164165
exerhmm1      168395
exract21      166039
exeroft2      278233
exerhmm2      283651
strength       39819
lmtjoin3      338395
arthdis2      341269
arthsocl      338578
joinpain      344065
seatbelt       38935
flushot6       40454
flshtmy2      297165
tetanus        83348
pneuvac3       84502
hivtst6        54593
hivtstd3      387292
whrtst10      362811
pdiabtst      267197
prediab1      257913
diabage2      457669
insulin       455380
bldsugar      456007
feetchk2      456497
doctdiab      457059
chkhemo3      458720
feetchk       457125
eyeexam       455970
diabeye       455881
diabedu       455487
painact2      491287
qlmentl2      491284
qlstres2      491288
qlhlth2       491310
medicare      178791
hlthcvrg      175883
delaymed      144721
dlyother      476506
nocov121      182112
lstcovrg      455021
drvisits      154152
medscost      142625
carercvd      153216
medbills      144297
ssbsugar      388580
ssbfrut2      388803
wtchsalt      363748
longwtch      421174
dradvise      363788
asthmage      490284
asattack      490773
aservist      491256
asdrvist      491273
asrchkup      490798
asactlim      490849
asymptom      490808
asnoslep      491068
asthmed3      490786
asinhalr      490797
harehab1      483230
strehab1      485611
cvdasprn      355557
aspunsaf      403283
rlivpain      445060
rduchart      446035
rducstrk      448602
arttoday      470286
arthwgt       470281
arthexer      470399
arthedu       470229
imfvplac      468752
hpvadvc2      478677
hpvadsht      490572
hadmam        461795
howlong       467431
profexam      461954
lengexam      465346
hadpap2       461962
lastpap2      464182
hadhyst2      462167
bldstool      411977
lstblds3      461248
hadsigm3      411822
hadsgco1      435281
lastsig3      434482
pcpsaad2      484775
pcpsadi1      484819
pcpsare1      484811
psatest1      484898
psatime       487957
pcpsars1      487984
pcpsade1      487913
pcdmdecn      490517
rrclass2      487870
rrcognt2      487924
rratwrk2      490238
rrhcare3      488388
rrphysm2      487832
rremtsm2      487833
misnervs      455630
mishopls      455615
misrstls      455738
misdeprd      455669
miseffrt      455915
miswtles      455728
misnowrk      455863
mistmnt       455781
mistrhlp      457246
misphlpf      457333
scntmony      429616
scntmeal      425695
scntpaid      459571
scntwrk1      459413
scntlpad      469779
scntlwk1      470493
scntvot1      426461
rcsgendr      421687
rcsrltn2      422041
casthdx2      425967
casthno2      482731
emtsuprt      480154
lsatisfy      480104
ctelnum1      360173
cellfon2      360144
cadult        360144
pvtresd2      360149
cclghous      490581
cstate        360148
landline      360154
pctcell       466929
qstver            11
qstlang          378
mscode        136643
X_ststr            4
X_strwt            6
X_rawrake          6
X_wt2rake          6
X_imprace          9
X_impnph      131639
X_impeduc     491772
X_impmrtl     491772
X_imphome     491772
X_chispnc     419789
X_crace1      420235
X_impcage     414828
X_impcrac     414827
X_impcsex     414826
X_cllcpwt     419607
X_dualuse         11
X_dualcor     431031
X_llcpwt2          6
X_llcpwt           7
X_rfhlth        1989
X_hcvu651     166598
X_rfhype5       1427
X_cholchk      14286
X_rfchol       71664
X_ltasth1       1567
X_casthm1       3430
X_asthms1       3429
X_drdxar1       2976
X_prace1        8376
X_mrace1        8375
X_hispanc       5439
X_race          8570
X_raceg21       8570
X_racegr3       8572
X_race_g1       8570
X_ageg5yr       4730
X_age65yr       4732
X_age_g           12
htin4           9510
htm4            7643
wtkg3          20685
X_bmi5         26727
X_bmi5cat      26727
X_rfbmi5       26729
X_chldcnt       2280
X_educag        2280
X_incomg       71428
X_smoker3      15333
X_rfsmok3      15335
drnkany5       19647
drocdy3_       19646
X_rfbing5      23731
X_drnkdy4      23881
X_drnkmo4      23882
X_rfdrhv4      23883
X_rfdrmn4     301354
X_rfdrwm4     214307
ftjuda1_       36211
frutda1_       33800
beanday_       37495
grenday_       35159
orngday_       36564
vegeda1_       38948
X_misfrtn         11
X_misvegn          9
X_frtresp         12
X_vegresp         10
X_frutsum      28702
X_vegesum      30165
X_frtlt1       28703
X_veglt1       30164
X_frt16           10
X_veg23           12
X_fruitex         10
X_vegetex         12
X_totinda      34034
metvl11_      175069
metvl21_      183999
maxvo2_         4729
fc60_           4730
actin11_      177754
actin21_      186563
padur1_       168396
padur2_       283652
pafreq1_      164169
pafreq2_      278234
X_minac11     170039
X_minac21     174656
strfreq_       39824
pamiss1_       34032
pamin11_      186263
pamin21_      193752
pa1min_       167961
pavig11_      181421
pavig21_      189965
pa1vigm_      166302
X_pacat1       76878
X_paindx1      67571
X_pa150r2      67570
X_pa300r2      76878
X_pa30021      76877
X_pastrng      39825
X_parec1       71486
X_pastae1      71489
X_lmtact1      14748
X_lmtwrk1      17622
X_lmtscl1      14931
X_rfseat2      38943
X_rfseat3      38941
X_flshot6     343079
X_pneumo2     349054
X_aidtst3      54595
X_age80           11
dtype: int64

In [ ]:
# Define a threshold for the maximum number of missing values
threshold = 250000

# Get the columns with missing values counts
missing_values = df.isnull().sum()

# Find columns with more than the specified threshold
columns_to_drop = missing_values[missing_values > threshold].index

# Drop the columns from the dataset
df = df.drop(columns=columns_to_drop)

In [ ]:
# Now, data will contain only columns with fewer than 250,000 missing values.

df

,Unnamed: 0,X_state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,X_psu,...,X_pastrng,X_parec1,X_pastae1,X_lmtact1,X_lmtwrk1,X_lmtscl1,X_rfseat2,X_rfseat3,X_aidtst3,X_age80
0,1,Alabama,January,1092013.0,January,9.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Told have arthritis and have limited usual act...,Told have arthritis and have limited work,Told have arthritis and social activities limi...,Always or almost always wear seat belt,Always wear seat belt,No,60.0
1,2,Alabama,January,1192013.0,January,19.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,Yes,50.0
2,3,Alabama,January,1192013.0,January,19.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Told have arthritis and have limited usual act...,Told have arthritis and have limited work,Told have arthritis and social activities limi...,Always or almost always wear seat belt,Always wear seat belt,Yes,55.0
3,4,Alabama,January,1112013.0,January,11.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,No,64.0
4,5,Alabama,February,2062013.0,February,6.0,2013.0,Completed interview,2.013001e+09,2.013001e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,No,66.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491770,491771,Puerto Rico,June,6212013.0,June,21.0,2013.0,Completed interview,2.013005e+09,2.013005e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Told have arthritis and no limited usual activ...,Told have arthritis and no limited work,Told have arthritis and social activities limi...,Always or almost always wear seat belt,Always wear seat belt,No,58.0
491771,491772,Puerto Rico,June,6222013.0,June,22.0,2013.0,Completed interview,2.013005e+09,2.013005e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Told have arthritis and have limited usual act...,Told have arthritis and have limited work,Told have arthritis and social activities not ...,Always or almost always wear seat belt,Always wear seat belt,No,62.0
491772,491773,Puerto Rico,July,8062013.0,August,6.0,2013.0,Partially completed interview,2.013005e+09,2.013005e+09,...,Did not meet muscle strengthening recommendations,Did not meet either guideline,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,Yes,37.0
491773,491774,Puerto Rico,July,8052013.0,August,5.0,2013.0,Completed interview,2.013005e+09,2.013005e+09,...,Did not meet muscle strengthening recommendations,Met aerobic guidelines only,Did not meet both guidelines,Not told they have arthritis,Not told they have arthritis,Not told they have arthritis,Always or almost always wear seat belt,Always wear seat belt,Yes,30.0
491774,491775,Puerto Rico,July,7282013.0,July,28.0,2013.0,Completed interview,2.013005e+09,2.013005e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
missing_values = df.isnull().sum()
print("Missing Values Count for Each Column:")
pd.set_option('display.max_rows', None)  # Display all rows
print(missing_values)
pd.reset_option('display.max_rows')  # Reset row display options

Missing Values Count for Each Column:
Unnamed: 0         0
X_state            0
fmonth             3
idate              2
imonth             3
iday               3
iyear              5
dispcode           5
seqno              3
X_psu              2
ctelenum          41
pvtresd1      131636
stateres      131642
cellfon3      135151
numadult      131651
nummen        131650
numwomen      131650
genhlth         1985
physhlth       10957
menthlth        8627
poorhlth      243153
hlthpln1        1904
persdoc2        1801
medcost         1221
checkup1        6305
sleptim1        7387
bphigh4         1420
bloodcho        9010
cholchk        73178
toldhi2        71662
cvdinfr4        2587
cvdcrhd4        4423
cvdstrk3        1467
asthma3         1559
chcscncr        1309
chcocncr        1148
chccopd1        2724
havarth3        2970
addepev2        2289
chckidny        1721
diabete3         832
veteran3         746
marital         3420
children        2274
educa           2274
employ1         3386
income2        71426
weight2        20675
height3         7623
numhhol2      134365
cpdemo1       135081
cpdemo4       227079
internet        4926
renthom1        8448
sex                7
qlactlm2       11329
useequip       10317
blind          11079
decide         12990
diffwalk       12764
diffdres       12122
diffalon       13350
smoke100       14920
usenow3        14018
alcday5        19644
fruitju1       36208
fruit1         33798
fvbeans        37492
fvgreen        35157
fvorang        36563
vegetab1       38947
exerany2       34029
exract11      160948
exeroft1      164165
exerhmm1      168395
exract21      166039
strength       39819
seatbelt       38935
flushot6       40454
tetanus        83348
pneuvac3       84502
hivtst6        54593
medicare      178791
hlthcvrg      175883
delaymed      144721
nocov121      182112
drvisits      154152
medscost      142625
carercvd      153216
medbills      144297
qstver            11
qstlang          378
mscode        136643
X_ststr            4
X_strwt            6
X_rawrake          6
X_wt2rake          6
X_imprace          9
X_impnph      131639
X_dualuse         11
X_llcpwt2          6
X_llcpwt           7
X_rfhlth        1989
X_hcvu651     166598
X_rfhype5       1427
X_cholchk      14286
X_rfchol       71664
X_ltasth1       1567
X_casthm1       3430
X_asthms1       3429
X_drdxar1       2976
X_prace1        8376
X_mrace1        8375
X_hispanc       5439
X_race          8570
X_raceg21       8570
X_racegr3       8572
X_race_g1       8570
X_ageg5yr       4730
X_age65yr       4732
X_age_g           12
htin4           9510
htm4            7643
wtkg3          20685
X_bmi5         26727
X_bmi5cat      26727
X_rfbmi5       26729
X_chldcnt       2280
X_educag        2280
X_incomg       71428
X_smoker3      15333
X_rfsmok3      15335
drnkany5       19647
drocdy3_       19646
X_rfbing5      23731
X_drnkdy4      23881
X_drnkmo4      23882
X_rfdrhv4      23883
X_rfdrwm4     214307
ftjuda1_       36211
frutda1_       33800
beanday_       37495
grenday_       35159
orngday_       36564
vegeda1_       38948
X_misfrtn         11
X_misvegn          9
X_frtresp         12
X_vegresp         10
X_frutsum      28702
X_vegesum      30165
X_frtlt1       28703
X_veglt1       30164
X_frt16           10
X_veg23           12
X_fruitex         10
X_vegetex         12
X_totinda      34034
metvl11_      175069
metvl21_      183999
maxvo2_         4729
fc60_           4730
actin11_      177754
actin21_      186563
padur1_       168396
pafreq1_      164169
X_minac11     170039
X_minac21     174656
strfreq_       39824
pamiss1_       34032
pamin11_      186263
pamin21_      193752
pa1min_       167961
pavig11_      181421
pavig21_      189965
pa1vigm_      166302
X_pacat1       76878
X_paindx1      67571
X_pa150r2      67570
X_pa300r2      76878
X_pa30021      76877
X_pastrng      39825
X_parec1       71486
X_pastae1      71489
X_lmtact1      14748
X_lmtwrk1      17622
X_lmtscl1      14931
X_rfseat2      38943
X_rfseat3      38941
X_aidtst3      54595
X_age80           11
dtype: int64

In [ ]:
"""Data correction for age group less than 30"""

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
missing_values_subset = df[df['X_age80'] < 30].isnull().sum()
missing_values_subset= missing_values_subset[missing_values_subset > 0]
print("Missing Values Count for Columns with Missing Values:")
print(missing_values_subset)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

Missing Values Count for Columns with Missing Values:
ctelenum         4
pvtresd1     36080
stateres     36081
cellfon3     36190
numadult     36082
nummen       36082
numwomen     36082
genhlth        115
physhlth       618
menthlth       627
poorhlth     21929
hlthpln1       666
persdoc2       320
medcost        113
checkup1      1043
sleptim1       395
bphigh4        138
bloodcho      3036
cholchk      26945
toldhi2      26461
cvdinfr4       128
cvdcrhd4       105
cvdstrk3        82
asthma3        174
chcscncr        73
chcocncr        73
chccopd1       220
havarth3       218
addepev2       268
chckidny        86
diabete3        84
veteran3        79
marital        373
children       214
educa          182
employ1        428
income2       8757
weight2       1508
height3        878
numhhol2     36176
cpdemo1      36189
cpdemo4      39052
internet       515
renthom1       944
qlactlm2      1324
useequip      1345
blind         1381
decide        1561
diffwalk      1538
diffdres      1572
diffalon      1662
smoke100      1829
usenow3       1795
alcday5       2395
fruitju1      4732
fruit1        4377
fvbeans       4612
fvgreen       4619
fvorang       4768
vegetab1      4984
exerany2      4817
exract11     13523
exeroft1     13778
exerhmm1     14007
exract21     14151
strength      5521
seatbelt      5456
flushot6      5792
tetanus      10383
pneuvac3     16372
hivtst6       6604
medicare     25293
hlthcvrg     24322
delaymed     17142
nocov121     25286
drvisits     17707
medscost     16950
carercvd     18426
medbills     17396
qstver           1
qstlang        127
mscode       36633
X_strwt          1
X_rawrake        1
X_wt2rake        1
X_imprace        1
X_impnph     36081
X_dualuse        2
X_llcpwt2        2
X_llcpwt         1
X_rfhlth       117
X_hcvu651      681
X_rfhype5      141
X_cholchk     3662
X_rfchol     26464
X_ltasth1      177
X_casthm1      500
X_asthms1      500
X_drdxar1      221
X_prace1      1045
X_mrace1      1044
X_hispanc      668
X_race         903
X_raceg21      902
X_racegr3      902
X_race_g1      902
X_ageg5yr       15
X_age65yr       15
X_age_g          2
htin4         1287
htm4           881
wtkg3         1512
X_bmi5        3485
X_bmi5cat     3485
X_rfbmi5      3486
X_chldcnt      216
X_educag       184
X_incomg      8759
X_smoker3     1852
X_rfsmok3     1852
drnkany5      2395
drocdy3_      2394
X_rfbing5     2919
X_drnkdy4     3083
X_drnkmo4     3083
X_rfdrhv4     3083
X_rfdrwm4    25801
ftjuda1_      4734
frutda1_      4378
beanday_      4613
grenday_      4620
orngday_      4769
vegeda1_      4984
X_misfrtn        2
X_misvegn        2
X_frtresp        2
X_vegresp        2
X_frutsum     3930
X_vegesum     4151
X_frtlt1      3931
X_veglt1      4150
X_frt16          1
X_veg23          3
X_fruitex        2
X_vegetex        1
X_totinda     4817
metvl11_     15105
metvl21_     16166
maxvo2_         14
fc60_           13
actin11_     15109
actin21_     16171
padur1_      14005
pafreq1_     13779
X_minac11    14119
X_minac21    15304
strfreq_      5521
pamiss1_      4816
pamin11_     15678
pamin21_     17123
pa1min_      13961
pavig11_     15130
pavig21_     16276
pa1vigm_     13705
X_pacat1      9370
X_paindx1     8378
X_pa150r2     8378
X_pa300r2     9371
X_pa30021     9369
X_pastrng     5522
X_parec1      8815
X_pastae1     8817
X_lmtact1      479
X_lmtwrk1      500
X_lmtscl1      481
X_rfseat2     5458
X_rfseat3     5456
X_aidtst3     6603
dtype: int64

In [ ]:
# Calculate missing values for columns in the subset of rows
missing_values_subset1 = df[(df['X_age80'] > 30) & (df['X_age80'] < 50)].isnull().sum()

# Filter for columns with missing values
missing_values_subset1 = missing_values_subset1[missing_values_subset1 > 0]

# Print the count of missing values for selected columns
print("Missing Values Count for Columns with Missing Values:")
print(missing_values_subset1)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

Missing Values Count for Columns with Missing Values:
ctelenum        12
pvtresd1     47781
stateres     47782
cellfon3     48507
numadult     47786
nummen       47786
numwomen     47786
genhlth        341
physhlth      1414
menthlth      1404
poorhlth     56093
hlthpln1       269
persdoc2       345
medcost        258
checkup1      1375
sleptim1      1018
bphigh4        217
bloodcho      2332
cholchk      22749
toldhi2      22460
cvdinfr4       380
cvdcrhd4       389
cvdstrk3       235
asthma3        260
chcscncr       187
chcocncr       234
chccopd1       395
havarth3       569
addepev2       506
chckidny       250
diabete3       193
veteran3       179
marital        784
children       791
educa          533
employ1        783
income2      10634
weight2       5078
height3       2102
numhhol2     48271
cpdemo1      48403
cpdemo4      60581
internet      1207
renthom1      1998
qlactlm2      2757
useequip      2717
blind         2787
decide        3162
diffwalk      3081
diffdres      3142
diffalon      3372
smoke100      3701
usenow3       3598
alcday5       4851
fruitju1      8694
fruit1        8204
fvbeans       8619
fvgreen       8467
fvorang       8779
vegetab1      9198
exerany2      8856
exract11     35292
exeroft1     35792
exerhmm1     36386
exract21     36508
strength     10092
seatbelt     10173
flushot6     10578
tetanus      20445
pneuvac3     26888
hivtst6      13564
medicare     46940
hlthcvrg     46341
delaymed     34465
nocov121     48375
drvisits     35478
medscost     33945
carercvd     37325
medbills     34261
qstlang        132
mscode       48953
X_impnph     47781
X_rfhlth       341
X_hcvu651     1247
X_rfhype5      217
X_cholchk     3193
X_rfchol     22460
X_ltasth1      260
X_casthm1      721
X_asthms1      721
X_drdxar1      569
X_prace1      2483
X_mrace1      2483
X_hispanc     1267
X_race        1933
X_raceg21     1933
X_racegr3     1933
X_race_g1     1933
X_ageg5yr     1012
X_age65yr     1012
htin4         2982
htm4          2109
wtkg3         5079
X_bmi5        7193
X_bmi5cat     7193
X_rfbmi5      7193
X_chldcnt      791
X_educag       533
X_incomg     10634
X_smoker3     3787
X_rfsmok3     3787
drnkany5      4851
drocdy3_      4851
X_rfbing5     5902
X_drnkdy4     5914
X_drnkmo4     5914
X_rfdrhv4     5914
X_rfdrwm4    53818
ftjuda1_      8694
frutda1_      8204
beanday_      8619
grenday_      8467
orngday_      8779
vegeda1_      9198
X_frutsum     7398
X_vegesum     7752
X_frtlt1      7398
X_veglt1      7752
X_totinda     8856
metvl11_     38605
metvl21_     40610
maxvo2_       1012
fc60_         1012
actin11_     39188
actin21_     41188
padur1_      36386
pafreq1_     35792
X_minac11    36617
X_minac21    38224
strfreq_     10092
pamiss1_      8856
pamin11_     40415
pamin21_     42572
pa1min_      36699
pavig11_     39314
pavig21_     41509
pa1vigm_     36295
X_pacat1     18491
X_paindx1    16425
X_pa150r2    16425
X_pa300r2    18491
X_pa30021    18491
X_pastrng    10092
X_parec1     17161
X_pastae1    17161
X_lmtact1     2063
X_lmtwrk1     2228
X_lmtscl1     2088
X_rfseat2    10173
X_rfseat3    10173
X_aidtst3    13564
dtype: int64

In [ ]:
# Calculate missing values for columns in the subset of rows
missing_values_subset2 = df[(df['X_age80'] > 50)].isnull().sum()

# Filter for columns with missing values
missing_values_subset2 = missing_values_subset2[missing_values_subset2 > 0]

# Print the count of missing values for selected columns
print("Missing Values Count for Columns with Missing Values:")
print(missing_values_subset2)

Missing Values Count for Columns with Missing Values:
ctelenum         18
pvtresd1      41374
stateres      41378
cellfon3      43960
numadult      41382
nummen        41383
numwomen      41383
genhlth        1479
physhlth       8712
menthlth       6379
poorhlth     157761
hlthpln1        921
persdoc2       1079
medcost         807
checkup1       3699
sleptim1       5804
bphigh4        1029
bloodcho       3305
cholchk       20388
toldhi2       19735
cvdinfr4       2018
cvdcrhd4       3865
cvdstrk3       1122
asthma3        1084
chcscncr       1007
chcocncr        795
chccopd1       2045
havarth3       2102
addepev2       1461
chckidny       1348
diabete3        532
veteran3        460
marital        2129
children       1165
educa          1480
employ1        2041
income2       50436
weight2       13375
height3        4329
numhhol2      43437
cpdemo1       43977
cpdemo4      119006
internet       3018
renthom1       5186
qlactlm2       6836
useequip       5851
blind          6484
decide         7797
diffwalk       7668
diffdres       6940
diffalon       7822
smoke100       8831
usenow3        8083
alcday5       11659
fruitju1      21530
fruit1        20001
fvbeans       22990
fvgreen       20818
fvorang       21724
vegetab1      23397
exerany2      19062
exract11     107439
exeroft1     109825
exerhmm1     113137
exract21     110501
strength      22752
seatbelt      21853
flushot6      22557
tetanus       49746
pneuvac3      37837
hivtst6       32516
medicare     100192
hlthcvrg      98961
delaymed      88451
nocov121     101906
drvisits      96129
medscost      87129
carercvd      92454
medbills      87989
qstlang          93
mscode        44471
X_impnph      41374
X_rfhlth       1479
X_hcvu651    164583
X_rfhype5      1029
X_cholchk      6951
X_rfchol      19735
X_ltasth1      1084
X_casthm1      2112
X_asthms1      2112
X_drdxar1      2102
X_prace1       4523
X_mrace1       4523
X_hispanc      3316
X_race         5448
X_raceg21      5448
X_racegr3      5448
X_race_g1      5448
X_ageg5yr      3659
X_age65yr      3659
htin4          4808
htm4           4336
wtkg3         13377
X_bmi5        15005
X_bmi5cat     15005
X_rfbmi5      15005
X_chldcnt      1165
X_educag       1480
X_incomg      50436
X_smoker3      9122
X_rfsmok3      9122
drnkany5      11659
drocdy3_      11659
X_rfbing5     14011
X_drnkdy4     13998
X_drnkmo4     13998
X_rfdrhv4     13998
X_rfdrwm4    127574
ftjuda1_      21530
frutda1_      20001
beanday_      22990
grenday_      20818
orngday_      21724
vegeda1_      23397
X_frutsum     16288
X_vegesum     17109
X_frtlt1      16288
X_veglt1      17109
X_totinda     19062
metvl11_     116251
metvl21_     121801
maxvo2_        3659
fc60_          3659
actin11_     118326
actin21_     123761
padur1_      113137
pafreq1_     109825
X_minac11    114400
X_minac21    115993
strfreq_      22752
pamiss1_      19062
pamin11_     124844
pamin21_     128404
pa1min_      112460
pavig11_     121832
pavig21_     126681
pa1vigm_     111538
X_pacat1      46459
X_paindx1     40512
X_pa150r2     40512
X_pa300r2     46459
X_pa30021     46459
X_pastrng     22752
X_parec1      43153
X_pastae1     43153
X_lmtact1     11878
X_lmtwrk1     14537
X_lmtscl1     12036
X_rfseat2     21853
X_rfseat3     21853
X_aidtst3     32516
dtype: int64

In [ ]:
"""dropping columns having high chance of biasing or no contribution for the model"""

columns_to_drop =  ['ctelenum'
		,'pvtresd1'
		,'stateres'
		,'cellfon3'
		,'numadult'
		,'nummen'
		,'numwomen'
		,'numhhol2'
		,'cpdemo1'
		,'exerany2'
		,'exract11'
		,'exract21'
		,'qstver'
		,'qstlang'
		,'mscode'
		,'X_hcvu651'
        ]

df = df.drop(columns=columns_to_drop)

In [ ]:
"""converting text column to numerial for convinence"""

replacement_mapping = {
    'Within past year': 1,
    'Within past 2 year': 2,
    'Within past 3 year': 3,
    '5 or more years ago': 5,
    'never': 0
}

columns_to_update = ['checkup1', 'cholchk']

df[columns_to_update] = df[columns_to_update].replace(replacement_mapping)

In [ ]:
"""Using Mean to fill columns"""

# # Define the list of columns to be converted to numeric
columns_to_fill = [				'genhlth'
		,'physhlth'
		,'menthlth'
		,'poorhlth'
		,'checkup1'
		,'sleptim1'
		,'cholchk'
		,'children'
		,'weight2'
		,'height3'
		,'cpdemo4'
		,'alcday5'
		,'fruitju1'
		,'fruit1'
		,'fvbeans'
		,'fvgreen'
		,'fvorang'
		,'vegetab1'
		,'exeroft1'
		,'exerhmm1'
		,'hlthcvrg'
		,'drvisits'
		,'X_strwt'
		,'X_rawrake'
		,'X_wt2rake'
		,'X_imprace'
		,'X_llcpwt2'
		,'X_llcpwt'
		,'htin4'
		,'htm4'
		,'wtkg3'
		,'X_bmi5'
		,'ftjuda1_'
		,'frutda1_'
		,'beanday_'
		,'grenday_'
		,'orngday_'
		,'vegeda1_'
		,'X_frutsum'
		,'X_vegesum'
		,'metvl11_'
		,'metvl21_'
		,'maxvo2_'
		,'fc60_'
		,'padur1_'
		,'pafreq1_'
		,'X_minac11'
		,'X_minac21'
		,'strfreq_'
		,'pamiss1_'
		,'pamin11_'
		,'pamin21_'
		,'pa1min_'
		,'pavig11_'
		,'pavig21_'
		,'pa1vigm_']

# # Convert the specified columns to numeric
df[columns_to_fill] = df[columns_to_fill].apply(pd.to_numeric, errors='coerce')
# Calculate the mean of each column
column_means = df[columns_to_fill].mean()

# Fill NaN values in the specified columns with the mean of each respective column
df[columns_to_fill] = df[columns_to_fill].fillna(column_means)

In [ ]:
columns_to_update = ['hlthpln1', 'persdoc2', 'medcost', 'bloodcho', 'cvdinfr4', 'cvdcrhd4', 'cvdstrk3', 'asthma3', 'chcscncr', 'chcocncr', 'chccopd1', 'havarth3', 'addepev2', 'chckidny', 'diabete3', 'veteran3', 'qlactlm2', 'useequip', 'blind', 'decide', 'diffwalk', 'diffdres', 'diffalon','hlthpln1']

# Update missing values to 'No' in the specified columns for rows where 'X_age80' is less than 30
df.loc[df['X_age80'] < 30, columns_to_update].fillna('No')

# Define the columns to update and their corresponding values
update_values = {
    'marital': 'Never married',
    'employ1': 'Out of work',
    'renthom1': 'Rent'
}

In [ ]:
# Update the missing values in the specified columns where 'X_age80' is less than 30
for column, value in update_values.items():
    df.loc[df['X_age80'] < 30, column] = df.loc[df['X_age80'] < 30, column].fillna(value)

columns_to_update_unknown = [
    'seatbelt', 'flushot6', 'tetanus', 'pneuvac3', 'hivtst6', 'X_impnph',
    'X_prace1', 'X_mrace1', 'X_hispanc', 'X_race', 'X_raceg21', 'X_racegr3',
    'X_race_g1', 'X_ageg5yr', 'X_age65yr', 'X_age_g', 'X_chldcnt', 'X_educag',
    'X_misfrtn', 'X_misvegn', 'X_frtresp', 'X_vegresp', 'X_pacat1', 'X_paindx1',
    'X_pa150r2', 'X_pa300r2', 'X_pa30021', 'X_pastrng', 'X_parec1', 'X_pastae1',
    'X_lmtact1', 'X_lmtwrk1', 'X_lmtscl1', 'X_rfseat2', 'bphigh4', 'marital',
    'educa', 'income2', 'renthom1', 'genhlth', 'persdoc2', 'medcost', 'bloodcho',
    'cvdinfr4', 'cvdcrhd4', 'cvdstrk3'
]

for column in columns_to_update_unknown:
    df[column] = df[column].fillna('unknown')

In [ ]:
import numpy as np

df['asthnow'] = np.where(df['asthma3'] == 'No', 'No', 'Yes')

# Update 'bpmeds' column based on 'bphigh4' condition
df.loc[df['bphigh4'] == 'No', 'bpmeds'] = 'No'
df.loc[df['bphigh4'] != 'No', 'bpmeds'] = 'Yes'

In [ ]:
# Update 'asthnow' column based on 'asthma3' condition
df.loc[df['asthma3'] == 'No', 'asthnow'] = 'No'
df.loc[df['asthma3'] != 'No', 'asthnow'] = 'Yes'

In [ ]:
# Update "toldhi2" column based on "bloodcho"
df['toldhi2'] = np.where(df['bloodcho'] == 'No', 'Yes', 'No')

In [ ]:
# Update 'employ1' column to 'Out of Work' where data has missing values
df.loc[df['employ1'].isnull(), 'employ1'] = 'Out of Work'

In [ ]:
# Update "internet" column to 'Yes' where data points are missing
df['internet'].fillna('Yes', inplace=True)

In [ ]:
# Update "renthom1" column to 'Rent' where data points are missing
df['renthom1'].fillna('Rent', inplace=True)

In [ ]:
missing_values = df.isnull().sum()
print("Missing Values Count for Each Column:")
pd.set_option('display.max_rows', None)  # Display all rows
print(missing_values)
pd.reset_option('display.max_rows')  # Reset row display options

Missing Values Count for Each Column:
Unnamed: 0         0
X_state            0
fmonth             3
idate              2
imonth             3
iday               3
iyear              5
dispcode           5
seqno              3
X_psu              2
genhlth            0
physhlth           0
menthlth           0
poorhlth           0
hlthpln1        1904
persdoc2           0
medcost            0
checkup1           0
sleptim1           0
bphigh4            0
bloodcho           0
cholchk            0
toldhi2            0
cvdinfr4           0
cvdcrhd4           0
cvdstrk3           0
asthma3         1559
chcscncr        1309
chcocncr        1148
chccopd1        2724
havarth3        2970
addepev2        2289
chckidny        1721
diabete3         832
veteran3         746
marital            0
children           0
educa              0
employ1            0
income2            0
weight2            0
height3            0
cpdemo4            0
internet           0
renthom1           0
sex                7
qlactlm2       11329
useequip       10317
blind          11079
decide         12990
diffwalk       12764
diffdres       12122
diffalon       13350
smoke100       14920
usenow3        14018
alcday5            0
fruitju1           0
fruit1             0
fvbeans            0
fvgreen            0
fvorang            0
vegetab1           0
exeroft1           0
exerhmm1           0
strength       39819
seatbelt           0
flushot6           0
tetanus            0
pneuvac3           0
hivtst6            0
medicare      178791
hlthcvrg           0
delaymed      144721
nocov121      182112
drvisits           0
medscost      142625
carercvd      153216
medbills      144297
X_ststr            4
X_strwt            0
X_rawrake          0
X_wt2rake          0
X_imprace     491775
X_impnph           0
X_dualuse         11
X_llcpwt2          0
X_llcpwt           0
X_rfhlth        1989
X_rfhype5       1427
X_cholchk      14286
X_rfchol       71664
X_ltasth1       1567
X_casthm1       3430
X_asthms1       3429
X_drdxar1       2976
X_prace1           0
X_mrace1           0
X_hispanc          0
X_race             0
X_raceg21          0
X_racegr3          0
X_race_g1          0
X_ageg5yr          0
X_age65yr          0
X_age_g            0
htin4              0
htm4               0
wtkg3              0
X_bmi5             0
X_bmi5cat      26727
X_rfbmi5       26729
X_chldcnt          0
X_educag           0
X_incomg       71428
X_smoker3      15333
X_rfsmok3      15335
drnkany5       19647
drocdy3_       19646
X_rfbing5      23731
X_drnkdy4      23881
X_drnkmo4      23882
X_rfdrhv4      23883
X_rfdrwm4     214307
ftjuda1_           0
frutda1_           0
beanday_           0
grenday_           0
orngday_           0
vegeda1_           0
X_misfrtn          0
X_misvegn          0
X_frtresp          0
X_vegresp          0
X_frutsum          0
X_vegesum          0
X_frtlt1       28703
X_veglt1       30164
X_frt16           10
X_veg23           12
X_fruitex         10
X_vegetex         12
X_totinda      34034
metvl11_           0
metvl21_           0
maxvo2_            0
fc60_              0
actin11_      177754
actin21_      186563
padur1_            0
pafreq1_           0
X_minac11          0
X_minac21          0
strfreq_           0
pamiss1_           0
pamin11_           0
pamin21_           0
pa1min_            0
pavig11_           0
pavig21_           0
pa1vigm_           0
X_pacat1           0
X_paindx1          0
X_pa150r2          0
X_pa300r2          0
X_pa30021          0
X_pastrng          0
X_parec1           0
X_pastae1          0
X_lmtact1          0
X_lmtwrk1          0
X_lmtscl1          0
X_rfseat2          0
X_rfseat3      38941
X_aidtst3      54595
X_age80           11
asthnow            0
bpmeds             0
dtype: int64

In [ ]:
# Filter and get the list of numerical columns
numerical_columns = df.select_dtypes(include=[float, int]).columns.tolist()

# Replace missing values in numerical columns with their mean
df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].mean())

# Replace missing values in categorical columns with their mode
categorical_columns = df.select_dtypes(include=[object]).columns.tolist()
df[categorical_columns] = df[categorical_columns].fillna(df[categorical_columns].mode().iloc[0])

# Save the preprocessed DataFrame to a new CSV file
df.to_csv('preprocessed_dataset.csv', index=False)

In [ ]:
df.shape

(491775, 177)

In [ ]:
missing_values = df.isnull().sum()
print("Missing Values Count for Each Column:")
pd.set_option('display.max_rows', None)  # Display all rows
print(missing_values)
pd.reset_option('display.max_rows')  # Reset row display options

Missing Values Count for Each Column:
Unnamed: 0         0
X_state            0
fmonth             0
idate              0
imonth             0
iday               0
iyear              0
dispcode           0
seqno              0
X_psu              0
genhlth            0
physhlth           0
menthlth           0
poorhlth           0
hlthpln1           0
persdoc2           0
medcost            0
checkup1           0
sleptim1           0
bphigh4            0
bloodcho           0
cholchk            0
toldhi2            0
cvdinfr4           0
cvdcrhd4           0
cvdstrk3           0
asthma3            0
chcscncr           0
chcocncr           0
chccopd1           0
havarth3           0
addepev2           0
chckidny           0
diabete3           0
veteran3           0
marital            0
children           0
educa              0
employ1            0
income2            0
weight2            0
height3            0
cpdemo4            0
internet           0
renthom1           0
sex                0
qlactlm2           0
useequip           0
blind              0
decide             0
diffwalk           0
diffdres           0
diffalon           0
smoke100           0
usenow3            0
alcday5            0
fruitju1           0
fruit1             0
fvbeans            0
fvgreen            0
fvorang            0
vegetab1           0
exeroft1           0
exerhmm1           0
strength           0
seatbelt           0
flushot6           0
tetanus            0
pneuvac3           0
hivtst6            0
medicare           0
hlthcvrg           0
delaymed           0
nocov121           0
drvisits           0
medscost           0
carercvd           0
medbills           0
X_ststr            0
X_strwt            0
X_rawrake          0
X_wt2rake          0
X_imprace     491775
X_impnph           0
X_dualuse          0
X_llcpwt2          0
X_llcpwt           0
X_rfhlth           0
X_rfhype5          0
X_cholchk          0
X_rfchol           0
X_ltasth1          0
X_casthm1          0
X_asthms1          0
X_drdxar1          0
X_prace1           0
X_mrace1           0
X_hispanc          0
X_race             0
X_raceg21          0
X_racegr3          0
X_race_g1          0
X_ageg5yr          0
X_age65yr          0
X_age_g            0
htin4              0
htm4               0
wtkg3              0
X_bmi5             0
X_bmi5cat          0
X_rfbmi5           0
X_chldcnt          0
X_educag           0
X_incomg           0
X_smoker3          0
X_rfsmok3          0
drnkany5           0
drocdy3_           0
X_rfbing5          0
X_drnkdy4          0
X_drnkmo4          0
X_rfdrhv4          0
X_rfdrwm4          0
ftjuda1_           0
frutda1_           0
beanday_           0
grenday_           0
orngday_           0
vegeda1_           0
X_misfrtn          0
X_misvegn          0
X_frtresp          0
X_vegresp          0
X_frutsum          0
X_vegesum          0
X_frtlt1           0
X_veglt1           0
X_frt16            0
X_veg23            0
X_fruitex          0
X_vegetex          0
X_totinda          0
metvl11_           0
metvl21_           0
maxvo2_            0
fc60_              0
actin11_           0
actin21_           0
padur1_            0
pafreq1_           0
X_minac11          0
X_minac21          0
strfreq_           0
pamiss1_           0
pamin11_           0
pamin21_           0
pa1min_            0
pavig11_           0
pavig21_           0
pa1vigm_           0
X_pacat1           0
X_paindx1          0
X_pa150r2          0
X_pa300r2          0
X_pa30021          0
X_pastrng          0
X_parec1           0
X_pastae1          0
X_lmtact1          0
X_lmtwrk1          0
X_lmtscl1          0
X_rfseat2          0
X_rfseat3          0
X_aidtst3          0
X_age80            0
asthnow            0
bpmeds             0
dtype: int64

In [ ]:
from scipy.stats import zscore

# 'df' is the DataFrame with numerical columns
numerical_columns = df.select_dtypes(include=[float, int]).columns.tolist()

# Calculating z-scores for each numerical column
z_scores = np.abs(zscore(df[numerical_columns]))

# Defining a threshold for identifying outliers (e.g., z_score_threshold = 3)
z_score_threshold = 3

# Find and remove rows containing outliers
outlier_rows = np.any(z_scores > z_score_threshold, axis=1)
df_no_outliers = df[~outlier_rows]

# Print the number of rows before and after handling outliers
print(f"Number of rows before handling outliers: {len(df)}")
print(f"Number of rows after handling outliers: {len(df_no_outliers)}")

Number of rows before handling outliers: 491775
Number of rows after handling outliers: 359655